"""Offline script to (re)compute Butterworth filter coefficients for config.py.

Run this on a development machine that has scipy installed whenever you change
DEVICE_SAMPLE_RATE, filter cutoffs, orders, or the notch frequency/quality in
config.py.  Paste the printed output into the FILTER COEFFICIENTS section of
config.py.

Usage:
    python scripts/compute_filter_coeffs.py
    python scripts/compute_filter_coeffs.py --fs 2000 --bp-low 20 --bp-high 450 \
        --notch 60 --notch-q 30 --lp-cutoff 10
"""

import argparse
import sys

try:
    from scipy.signal import butter
except ImportError:
    sys.exit("scipy is required to run this script: pip install scipy")

import numpy as np


def fmt_list(arr, indent=4):
    """Format a float list as a compact multi-line Python literal."""
    items = [repr(float(v)) for v in arr]
    # Pack 4 items per line
    lines = []
    for i in range(0, len(items), 4):
        lines.append(", ".join(items[i:i + 4]))
    pad = " " * indent
    inner = (",\n" + pad).join(lines)
    return f"[\n{pad}{inner},\n]"


def compute(fs, bp_low, bp_high, bp_order, notch_freq, notch_q, notch_order,
            lp_cutoff, lp_order):
    nyq = fs / 2

    b_bp4, a_bp4 = butter(bp_order,   [bp_low / nyq, bp_high / nyq], btype='band')
    b_bp1, a_bp1 = butter(1,           [bp_low / nyq, bp_high / nyq], btype='band')
    b_lp,  a_lp  = butter(lp_order,    lp_cutoff / nyq,               btype='low')

    wl = notch_freq / nyq - notch_freq / nyq / notch_q
    wh = notch_freq / nyq + notch_freq / nyq / notch_q
    b_notch, a_notch = butter(notch_order, [wl, wh], btype='bandstop')

    print(f"# ---- Generated by scripts/compute_filter_coeffs.py ----")
    print(f"# DEVICE_SAMPLE_RATE = {fs} Hz")
    print(f"# Bandpass: {bp_low}-{bp_high} Hz, order {bp_order}")
    print(f"# Lowpass:  {lp_cutoff} Hz, order {lp_order}  (TKEO smoothing)")
    print(f"# Notch:    {notch_freq} Hz, Q={notch_q}, order {notch_order}")
    print()
    print(f"# butter({bp_order}, [{bp_low}/{int(nyq)}, {bp_high}/{int(nyq)}], btype='band')")
    print(f"BANDPASS_4_B = {fmt_list(b_bp4)}")
    print(f"BANDPASS_4_A = {fmt_list(a_bp4)}")
    print()
    print(f"# butter(1, [{bp_low}/{int(nyq)}, {bp_high}/{int(nyq)}], btype='band')  — short-data fallback")
    print(f"BANDPASS_1_B = {fmt_list(b_bp1)}")
    print(f"BANDPASS_1_A = {fmt_list(a_bp1)}")
    print()
    print(f"# butter({lp_order}, {lp_cutoff}/{int(nyq)}, btype='low')  — TKEO envelope smoothing")
    print(f"LOWPASS_{int(lp_cutoff)}_{lp_order}_B = {fmt_list(b_lp)}")
    print(f"LOWPASS_{int(lp_cutoff)}_{lp_order}_A = {fmt_list(a_lp)}")
    print()
    print(f"# butter({notch_order}, [{wl:.6f}, {wh:.6f}], btype='bandstop')  — {notch_freq} Hz notch")
    print(f"NOTCH_{int(notch_freq)}_B = {fmt_list(b_notch)}")
    print(f"NOTCH_{int(notch_freq)}_A = {fmt_list(a_notch)}")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--fs',        type=float, default=2000, help='Device sample rate (Hz)')
    p.add_argument('--bp-low',    type=float, default=20,   help='Bandpass lower cutoff (Hz)')
    p.add_argument('--bp-high',   type=float, default=450,  help='Bandpass upper cutoff (Hz)')
    p.add_argument('--bp-order',  type=int,   default=4,    help='Bandpass filter order')
    p.add_argument('--notch',     type=float, default=60,   help='Notch frequency (Hz)')
    p.add_argument('--notch-q',   type=float, default=30,   help='Notch Q factor')
    p.add_argument('--notch-ord', type=int,   default=2,    help='Notch filter order')
    p.add_argument('--lp-cutoff', type=float, default=10,   help='Lowpass cutoff for TKEO smoothing (Hz)')
    p.add_argument('--lp-order',  type=int,   default=4,    help='Lowpass filter order')
    args = p.parse_args()

    compute(args.fs, args.bp_low, args.bp_high, args.bp_order,
            args.notch, args.notch_q, args.notch_ord,
            args.lp_cutoff, args.lp_order)


if __name__ == '__main__':
    main()
