"""Application configuration loader.

Reads config.json (adjacent to this file) and exposes all values as
module-level constants with the same SCREAMING_SNAKE_CASE names used
throughout the codebase.  Edit config.json to change tuneable parameters.

Filter coefficients in config.json were generated by
scripts/compute_filter_coeffs.py at DEVICE_SAMPLE_RATE = 2000 Hz.
Re-run that script and update config.json whenever you change the
sample rate or cutoffs.
"""

import json
import os

_here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_here, 'config.json'), 'r') as _f:
    _raw = json.load(_f)

# -- Build flags ---------------------------------------------------------------
EMULATOR_BUILD = _raw['build']['emulator_build']

# -- Device --------------------------------------------------------------------
DEVICE_SAMPLE_RATE     = _raw['device']['sample_rate']
DEVICE_CHANNELS        = _raw['device']['channels']
DEVICE_HOST            = _raw['device']['host']
DEVICE_GATEWAY_IP      = _raw['device']['gateway_ip']
DEVICE_PORT            = _raw['device']['port']
DEVICE_CONNECT_TIMEOUT = _raw['device']['connect_timeout']
DEVICE_FSAMP           = _raw['device']['fsamp']
DEVICE_NCH             = _raw['device']['nch']
DEVICE_MODE            = _raw['device']['mode']
DEVICE_HPF             = _raw['device']['hpf']
NETWORK_CHECK_TIMEOUT  = _raw['device']['network_check_timeout']

# -- HD-EMG grid ---------------------------------------------------------------
HDSEMG_CHANNELS  = _raw['hdsemg']['channels']
HDSEMG_GRID_ROWS = _raw['hdsemg']['grid_rows']
HDSEMG_GRID_COLS = _raw['hdsemg']['grid_cols']

# -- Filter parameters ---------------------------------------------------------
BANDPASS_LOW_HZ           = _raw['filter']['bandpass_low_hz']
BANDPASS_HIGH_HZ          = _raw['filter']['bandpass_high_hz']
BANDPASS_ORDER            = _raw['filter']['bandpass_order']
NOTCH_FREQ_HZ             = _raw['filter']['notch_freq_hz']
NOTCH_QUALITY             = _raw['filter']['notch_quality']
NOTCH_ORDER               = _raw['filter']['notch_order']
FILTER_MIN_SAMPLES_ORDER4 = _raw['filter']['min_samples_order4']
FILTER_MIN_SAMPLES_ORDER1 = _raw['filter']['min_samples_order1']
NOTCH_MIN_SAMPLES         = _raw['filter']['notch_min_samples']

# -- Pre-computed filter coefficients ------------------------------------------
BANDPASS_4_B   = _raw['filter_coefficients']['bandpass_4_b']
BANDPASS_4_A   = _raw['filter_coefficients']['bandpass_4_a']
BANDPASS_1_B   = _raw['filter_coefficients']['bandpass_1_b']
BANDPASS_1_A   = _raw['filter_coefficients']['bandpass_1_a']
LOWPASS_10_4_B = _raw['filter_coefficients']['lowpass_10_4_b']
LOWPASS_10_4_A = _raw['filter_coefficients']['lowpass_10_4_a']
NOTCH_60_B     = _raw['filter_coefficients']['notch_60_b']
NOTCH_60_A     = _raw['filter_coefficients']['notch_60_a']

# -- Real-time plot ------------------------------------------------------------
PLOT_DISPLAY_SAMPLES = _raw['plot']['display_samples']
PLOT_DOWNSAMPLE      = _raw['plot']['downsample']
PLOT_CHANNEL_INDEX   = _raw['plot']['channel_index']
PLOT_BG_RGBA         = tuple(_raw['plot']['bg_rgba'])
PLOT_LINE_RGBA       = tuple(_raw['plot']['line_rgba'])
PLOT_TIME_WINDOW_PRESETS = _raw['plot'].get('time_window_presets', [
    {'label': '2s', 'display_samples': 4000, 'downsample': 4},
])
PLOT_DEFAULT_TIME_IDX   = _raw['plot'].get('default_time_window_idx', 0)

# -- Calibration ---------------------------------------------------------------
CALIBRATION_REST_DURATION  = _raw['calibration']['rest_duration']
CALIBRATION_MVC_DURATION   = _raw['calibration']['mvc_duration']
CALIBRATION_THRESHOLD_FRAC = _raw['calibration']['threshold_frac']
CALIBRATION_DISMISS_DELAY  = _raw['calibration']['dismiss_delay']
CALIBRATION_PROGRESS_FPS   = _raw['calibration']['progress_fps']

# -- Feature analysis defaults -------------------------------------------------
FEATURE_BANDPASS_LOW          = _raw['features']['bandpass_low']
FEATURE_BANDPASS_HIGH         = _raw['features']['bandpass_high']
FEATURE_SMOOTH_CUTOFF         = _raw['features']['smooth_cutoff']
FEATURE_BASELINE_DURATION     = _raw['features']['baseline_duration']
FEATURE_K_THRESHOLD           = _raw['features']['k_threshold']
FEATURE_AMPLITUDE_DIVISOR     = _raw['features']['amplitude_divisor']
FEATURE_MIN_PEAK_DISTANCE_SEC = _raw['features']['min_peak_distance_sec']
FEATURE_BACKTRACK_K           = _raw['features']['backtrack_k']
FEATURE_MIN_BURST_DURATION    = _raw['features']['min_burst_duration']
FEATURE_FATIGUE_RMS_THRESHOLD = _raw['features']['fatigue_rms_threshold']
FEATURE_FATIGUE_MF_THRESHOLD  = _raw['features']['fatigue_mf_threshold']
FEATURE_WINDOW_DURATION       = _raw['features']['window_duration']
FEATURE_STEP_DURATION         = _raw['features']['step_duration']
FEATURE_BILATERAL_WINDOW_SEC  = _raw['features']['bilateral_window_sec']
FEATURE_BILATERAL_STEP_SEC    = _raw['features']['bilateral_step_sec']

# -- Colors --------------------------------------------------------------------
MULTI_TRACK_COLORS   = [tuple(c) for c in _raw['colors']['multi_track']]
HEATMAP_COLD_RGB     = tuple(_raw['colors']['heatmap_cold_rgb'])
HEATMAP_HOT_RGB      = tuple(_raw['colors']['heatmap_hot_rgb'])
BTN_STREAM_IDLE      = tuple(_raw['colors']['btn_stream_idle'])
BTN_RECORD_IDLE      = tuple(_raw['colors']['btn_record_idle'])
BTN_RECORD_SAVING    = tuple(_raw['colors']['btn_record_saving'])
BTN_LIVE_MODE        = tuple(_raw['colors']['btn_live_mode'])
BTN_ANALYSIS_MODE    = tuple(_raw['colors']['btn_analysis_mode'])
BATTERY_LOW_COLOR    = tuple(_raw['colors']['battery_low'])
BATTERY_MED_COLOR    = tuple(_raw['colors']['battery_med'])
BATTERY_OK_COLOR     = tuple(_raw['colors']['battery_ok'])
CONTRACTION_ACTIVE   = tuple(_raw['colors']['contraction_active'])
CONTRACTION_INACTIVE = tuple(_raw['colors']['contraction_inactive'])

# -- UI timing -----------------------------------------------------------------
UPDATE_RATE_MS         = _raw['ui']['update_rate_ms']
RENDER_FPS             = _raw['ui']['render_fps']
HEATMAP_BUFFER_SAMPLES = _raw['ui']['heatmap_buffer_samples']
BATTERY_POLL_INTERVAL  = _raw['ui']['battery_poll_interval']
BATTERY_LOW_THRESHOLD  = _raw['ui']['battery_low_threshold']
BATTERY_MED_THRESHOLD  = _raw['ui']['battery_med_threshold']

# -- Data receiver -------------------------------------------------------------
PACKET_SIZE_DIVISOR = _raw['data_receiver']['packet_size_divisor']
SOCKET_TIMEOUT      = _raw['data_receiver']['socket_timeout']
FPS_LOG_INTERVAL    = _raw['data_receiver']['fps_log_interval']

# -- Recording -----------------------------------------------------------------
RECORDING_MAX_SAMPLES = _raw['recording']['max_samples']

# -- Session metadata ----------------------------------------------------------
SESSION_MUSCLE_GROUPS  = _raw['session']['muscle_groups']
SESSION_EXERCISE_TYPES = _raw['session']['exercise_types']

# -- Longitudinal tracking -----------------------------------------------------
LONGITUDINAL_MAX_SESSIONS = _raw['longitudinal']['max_sessions']

# -- Safety --------------------------------------------------------------------
LATENCY_WARNING_MS          = _raw['safety']['latency_warning_threshold_ms']
LATENCY_ROLLING_WINDOW      = _raw['safety']['latency_rolling_window']
DISCONNECT_WARNING_SEC      = _raw['safety']['disconnect_warning_sec']
ADC_RAIL_VALUE              = _raw['safety']['adc_rail_value']
CLIPPING_FRACTION_THRESHOLD = _raw['safety']['clipping_fraction_threshold']

# -- Paths ---------------------------------------------------------------------
ANDROID_PACKAGE_NAME   = _raw['paths']['android_package_name']
DATA_DIR_NAME          = _raw['paths']['data_dir_name']
DESKTOP_DATA_DIR_NAME  = _raw['paths']['desktop_data_dir_name']
RECORDINGS_DIR_NAME    = _raw['paths']['recordings_dir_name']
