"""Application configuration loader.

Reads config.json (adjacent to this file) and exposes all values as
module-level constants with the same SCREAMING_SNAKE_CASE names used
throughout the codebase.  Edit config.json to change tuneable parameters.

Filter coefficients in config.json were generated by
scripts/compute_filter_coeffs.py at DEVICE_SAMPLE_RATE = 2000 Hz.
Re-run that script and update config.json whenever you change the
sample rate or cutoffs.
"""

import json
import os

_here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_here, 'config.json'), 'r') as _f:
    _raw = json.load(_f)

# -- Build flags ---------------------------------------------------------------
EMULATOR_BUILD = _raw['build']['emulator_build']

# -- Device --------------------------------------------------------------------
DEVICE_SAMPLE_RATE     = _raw['device']['sample_rate']
DEVICE_CHANNELS        = _raw['device']['channels']
DEVICE_HOST            = _raw['device']['host']
DEVICE_GATEWAY_IP      = _raw['device']['gateway_ip']
DEVICE_PORT            = _raw['device']['port']
DEVICE_CONNECT_TIMEOUT = _raw['device']['connect_timeout']
DEVICE_FSAMP           = _raw['device']['fsamp']
DEVICE_NCH             = _raw['device']['nch']
DEVICE_MODE            = _raw['device']['mode']
DEVICE_HPF             = _raw['device']['hpf']
NETWORK_CHECK_TIMEOUT  = _raw['device']['network_check_timeout']

# -- HD-EMG grid ---------------------------------------------------------------
HDSEMG_CHANNELS  = _raw['hdsemg']['channels']
HDSEMG_GRID_ROWS = _raw['hdsemg']['grid_rows']
HDSEMG_GRID_COLS = _raw['hdsemg']['grid_cols']

# -- Adapter (ribbon cable) ---------------------------------------------------
# "ad1x64sp"  — single 64-ch cable, 8x8 grid, no remap needed.
# "ad2x32sp"  — two 32-ch cables side by side (each 8 rows × 4 cols).
#               Adapter A (raw ch 0-31) = left half, Adapter B (raw ch 32-63) = right half.
#
# 32-ch adapter physical layout (1-indexed):
#   [[1,9,17,25], [2,10,18,26], ... [8,16,24,32]]
#
# Dual adapter side-by-side → 8×8 physical grid.
# 64-ch grid physical layout (1-indexed):
#   [[64,56,48,40,32,24,16,8], ... [57,49,41,33,25,17,9,1]]
#
# For each physical position [row][col]:
#   64-ch logical index (0-idx) = (7 - col) * 8 + (7 - row)
#   raw adapter index (0-idx):
#     col < 4 (adapter A): col * 8 + row
#     col >= 4 (adapter B): 32 + (col - 4) * 8 + row
#
# Set "channel_map" to a 64-element list in config.json to override the built-in preset.
# The map is indexed by logical channel (0-based): channel_map[logical] = raw_index.
ADAPTER_TYPE = _raw.get('adapter', {}).get('type', 'ad1x64sp')
_adapter_map_override = _raw.get('adapter', {}).get('channel_map', None)

# Built-in presets — empirically verified channel maps per adapter type.
_ADAPTER_PRESETS = {
    'ad2x32sp': [
        19, 18, 17, 16, 15, 14, 13, 12,  # logical 1-8
         3,  2,  1,  0, 31, 30, 29, 28,  # logical 9-16
        27, 26, 25, 24, 11, 10,  9,  8,  # logical 17-24
         7,  6,  5,  4, 23, 22, 21, 20,  # logical 25-32
        51, 50, 49, 48, 47, 46, 45, 44,  # logical 33-40
        35, 34, 33, 32, 63, 62, 61, 60,  # logical 41-48
        59, 58, 57, 56, 43, 42, 41, 40,  # logical 49-56
        39, 38, 37, 36, 55, 54, 53, 52,  # logical 57-64
    ],
}

if _adapter_map_override is not None:
    ADAPTER_CHANNEL_MAP = list(_adapter_map_override)
elif ADAPTER_TYPE in _ADAPTER_PRESETS:
    ADAPTER_CHANNEL_MAP = list(_ADAPTER_PRESETS[ADAPTER_TYPE])
else:
    ADAPTER_CHANNEL_MAP = None  # no remap for ad1x64sp

# Dead raw channel offsets per adapter type — device sends zeros on these pins
# because the adapter connector does not make contact with them.
# Offsets are relative to each 32-channel block: 4-11 within each block are unused.
_ADAPTER_DEAD_RAW = {
    'ad2x32sp': frozenset(range(4, 12)) | frozenset(range(36, 44)),
}
_dead_raw = _ADAPTER_DEAD_RAW.get(ADAPTER_TYPE, frozenset())
if ADAPTER_CHANNEL_MAP is not None and _dead_raw:
    DEAD_CHANNELS = frozenset(
        i for i, raw in enumerate(ADAPTER_CHANNEL_MAP) if raw in _dead_raw
    )
else:
    DEAD_CHANNELS = frozenset()

# How dead cells are rendered on the heatmap. Only meaningful when DEAD_CHANNELS
# is non-empty (i.e. ad2x32sp). None for ad1x64sp (no dead channels).
# "removed" — dark purple-grey fill + × overlay + em-dash label (default)
# "raw"     — rendered like a live cell; always appears cold since device sends 0
# "demo"    — rendered at the mean RMS of all active channels
ADAPTER_HEATMAP_MODE = (
    _raw.get('adapter', {}).get('heatmap_mode', 'removed')
    if DEAD_CHANNELS else None
)

# -- Filter parameters ---------------------------------------------------------
BANDPASS_LOW_HZ           = _raw['filter']['bandpass_low_hz']
BANDPASS_HIGH_HZ          = _raw['filter']['bandpass_high_hz']
BANDPASS_ORDER            = _raw['filter']['bandpass_order']
NOTCH_FREQ_HZ             = _raw['filter']['notch_freq_hz']
NOTCH_QUALITY             = _raw['filter']['notch_quality']
NOTCH_ORDER               = _raw['filter']['notch_order']
FILTER_MIN_SAMPLES_ORDER4 = _raw['filter']['min_samples_order4']
FILTER_MIN_SAMPLES_ORDER1 = _raw['filter']['min_samples_order1']
NOTCH_MIN_SAMPLES         = _raw['filter']['notch_min_samples']

# -- Pre-computed filter coefficients ------------------------------------------
BANDPASS_4_B   = _raw['filter_coefficients']['bandpass_4_b']
BANDPASS_4_A   = _raw['filter_coefficients']['bandpass_4_a']
BANDPASS_1_B   = _raw['filter_coefficients']['bandpass_1_b']
BANDPASS_1_A   = _raw['filter_coefficients']['bandpass_1_a']
LOWPASS_10_4_B = _raw['filter_coefficients']['lowpass_10_4_b']
LOWPASS_10_4_A = _raw['filter_coefficients']['lowpass_10_4_a']
NOTCH_60_B     = _raw['filter_coefficients']['notch_60_b']
NOTCH_60_A     = _raw['filter_coefficients']['notch_60_a']

# -- Real-time plot ------------------------------------------------------------
PLOT_DISPLAY_SAMPLES = _raw['plot']['display_samples']
PLOT_DOWNSAMPLE      = _raw['plot']['downsample']
PLOT_CHANNEL_INDEX   = _raw['plot']['channel_index']
PLOT_BG_RGBA         = tuple(_raw['plot']['bg_rgba'])
PLOT_LINE_RGBA       = tuple(_raw['plot']['line_rgba'])
PLOT_TIME_WINDOW_PRESETS = _raw['plot'].get('time_window_presets', [
    {'label': '2s', 'display_samples': 4000, 'downsample': 4},
])
PLOT_DEFAULT_TIME_IDX   = _raw['plot'].get('default_time_window_idx', 0)

# -- Calibration ---------------------------------------------------------------
CALIBRATION_REST_DURATION   = _raw['calibration']['rest_duration']
CALIBRATION_MVC_DURATION    = _raw['calibration']['mvc_duration']
CALIBRATION_THRESHOLD_FRAC  = _raw['calibration']['threshold_frac']
CALIBRATION_DISMISS_DELAY   = _raw['calibration']['dismiss_delay']
CALIBRATION_PROGRESS_FPS    = _raw['calibration']['progress_fps']
CROSSTALK_DURATION             = _raw['calibration']['crosstalk_duration']
CROSSTALK_THRESHOLD_K          = _raw['calibration']['crosstalk_threshold_k']
CALIBRATION_VERIFY_DURATION    = _raw['calibration']['verification_duration']
CALIBRATION_VERIFY_ACTIVE_FRAC = _raw['calibration']['verification_active_fraction']

# -- Feature analysis defaults -------------------------------------------------
FEATURE_BANDPASS_LOW          = _raw['features']['bandpass_low']
FEATURE_BANDPASS_HIGH         = _raw['features']['bandpass_high']
FEATURE_SMOOTH_CUTOFF         = _raw['features']['smooth_cutoff']
FEATURE_BASELINE_DURATION     = _raw['features']['baseline_duration']
FEATURE_K_THRESHOLD           = _raw['features']['k_threshold']
FEATURE_AMPLITUDE_DIVISOR     = _raw['features']['amplitude_divisor']
FEATURE_MIN_PEAK_DISTANCE_SEC = _raw['features']['min_peak_distance_sec']
FEATURE_BACKTRACK_K           = _raw['features']['backtrack_k']
FEATURE_MIN_BURST_DURATION    = _raw['features']['min_burst_duration']
FEATURE_FATIGUE_RMS_THRESHOLD = _raw['features']['fatigue_rms_threshold']
FEATURE_FATIGUE_MF_THRESHOLD  = _raw['features']['fatigue_mf_threshold']
FEATURE_WINDOW_DURATION       = _raw['features']['window_duration']
FEATURE_STEP_DURATION         = _raw['features']['step_duration']
FEATURE_BILATERAL_WINDOW_SEC  = _raw['features']['bilateral_window_sec']
FEATURE_BILATERAL_STEP_SEC    = _raw['features']['bilateral_step_sec']

# -- Colors --------------------------------------------------------------------
MULTI_TRACK_COLORS   = [tuple(c) for c in _raw['colors']['multi_track']]
HEATMAP_COLD_RGB     = tuple(_raw['colors']['heatmap_cold_rgb'])
HEATMAP_HOT_RGB      = tuple(_raw['colors']['heatmap_hot_rgb'])
BTN_STREAM_IDLE      = tuple(_raw['colors']['btn_stream_idle'])
BTN_STREAM_ACTIVE    = tuple(_raw['colors']['btn_stream_active'])
BTN_RECORD_IDLE      = tuple(_raw['colors']['btn_record_idle'])
BTN_RECORD_ACTIVE    = tuple(_raw['colors']['btn_record_active'])
BTN_RECORD_SAVING    = tuple(_raw['colors']['btn_record_saving'])
BTN_LIVE_MODE        = tuple(_raw['colors']['btn_live_mode'])
BTN_ANALYSIS_MODE    = tuple(_raw['colors']['btn_analysis_mode'])
BATTERY_LOW_COLOR    = tuple(_raw['colors']['battery_low'])
BATTERY_MED_COLOR    = tuple(_raw['colors']['battery_med'])
BATTERY_OK_COLOR     = tuple(_raw['colors']['battery_ok'])
CONTRACTION_ACTIVE   = tuple(_raw['colors']['contraction_active'])
CONTRACTION_INACTIVE = tuple(_raw['colors']['contraction_inactive'])

# -- UI timing -----------------------------------------------------------------
UPDATE_RATE_MS         = _raw['ui']['update_rate_ms']
RENDER_FPS             = _raw['ui']['render_fps']
HEATMAP_BUFFER_SAMPLES = _raw['ui']['heatmap_buffer_samples']
BATTERY_POLL_INTERVAL  = _raw['ui']['battery_poll_interval']
BATTERY_LOW_THRESHOLD  = _raw['ui']['battery_low_threshold']
BATTERY_MED_THRESHOLD  = _raw['ui']['battery_med_threshold']

# -- Data receiver -------------------------------------------------------------
PACKET_SIZE_DIVISOR = _raw['data_receiver']['packet_size_divisor']
SOCKET_TIMEOUT      = _raw['data_receiver']['socket_timeout']
FPS_LOG_INTERVAL    = _raw['data_receiver']['fps_log_interval']

# -- Recording -----------------------------------------------------------------
RECORDING_MAX_SAMPLES = _raw['recording']['max_samples']

# -- Session metadata ----------------------------------------------------------
SESSION_MUSCLE_GROUPS  = _raw['session']['muscle_groups']
SESSION_EXERCISE_TYPES = _raw['session']['exercise_types']

# -- Longitudinal tracking -----------------------------------------------------
LONGITUDINAL_MAX_SESSIONS = _raw['longitudinal']['max_sessions']

# -- Safety --------------------------------------------------------------------
LATENCY_WARNING_MS          = _raw['safety']['latency_warning_threshold_ms']
LATENCY_ROLLING_WINDOW      = _raw['safety']['latency_rolling_window']
DISCONNECT_WARNING_SEC      = _raw['safety']['disconnect_warning_sec']
ADC_RAIL_VALUE              = _raw['safety']['adc_rail_value']

# -- Paths ---------------------------------------------------------------------
ANDROID_PACKAGE_NAME   = _raw['paths']['android_package_name']
DATA_DIR_NAME          = _raw['paths']['data_dir_name']
DESKTOP_DATA_DIR_NAME  = _raw['paths']['desktop_data_dir_name']
RECORDINGS_DIR_NAME    = _raw['paths']['recordings_dir_name']
